swagger: "2.0"
info:
  version: 1.0.0
  title: balanced-gym-app
  description: Balanced Gym App
basePath: /api/v1
tags:
  - name: All

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /routines:
    get:
      tags:
        - All
      description: Fetch all routines
      responses:
        200:
          description: Returns all routines

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification