swagger: '2.0'
info:
  description: Balanced Gym App
  title: balanced-gym-app
  version: 1.0.0
basePath: /api/v1
paths:
  '/routine/{routineId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - All
      description: Fetch the routine with the given Id
  '/routine/{routineId}/muscleGroup/{muscleGroupId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          required: true
          type: string
          x-example: 5dde9b568603d000157b627d
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - All
      description: Fetch the muscleGroup with the given IDs
  '/routine/{routineId}/muscleGroup/{muscleGroupId}/target/{targetId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          required: true
          type: string
          x-example: 5dde9b568603d000157b627d
        - in: path
          name: targetId
          required: true
          type: string
          x-example: 5a55152ad9b873001457578f
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - All
      description: Fetch the target with the given IDs
  /routines:
    get:
      parameters: []
      responses:
        '200':
          description: Returns all routines
      tags:
        - All
      description: Fetch all routines
  /spec:
    get:
      parameters: []
      responses:
        '200':
          description: Return the API specification
      tags:
        - Specification
tags:
  - name: All

