openapi: 3.0.0
info:
  version: 1.0.0
  title: balanced-gym-app
  description: Balanced Gym App
tags:
  - name: Routine
  - name: Serie
  - name: Exercise
paths:
  /routines:
    get:
      tags:
        - Routine
      description: Fetch all routines
      responses:
        "200":
          description: Returns all routines
  /routine/{routineId}:
    get:
      tags:
        - Routine
      description: Fetch the routine with the given Id
      parameters:
        - in: path
          name: routineId
          schema:
            type: string
          required: true
          example: 59f0c59d4e55c40d38868034
      responses:
        "200":
          description: Returns the routine with ID
  /routine/{routineId}/muscleGroup/{muscleGroupId}:
    get:
      tags:
        - Routine
      description: Fetch the muscleGroup with the given IDs
      parameters:
        - in: path
          name: routineId
          schema:
            type: string
          required: true
          example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          schema:
            type: string
          required: true
          example: 5dde9b568603d000157b627d
      responses:
        "200":
          description: Returns the routine with ID
  /routine/{routineId}/muscleGroup/{muscleGroupId}/target/{targetId}:
    get:
      tags:
        - Routine
      description: Fetch the target with the given IDs
      parameters:
        - in: path
          name: routineId
          schema:
            type: string
          required: true
          example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          schema:
            type: string
          required: true
          example: 5dde9b568603d000157b627d
        - in: path
          name: targetId
          schema:
            type: string
          required: true
          example: 5a55152ad9b873001457578f
      responses:
        "200":
          description: Returns the target with ID
  /exercise/{exerciseId}:
    get:
      tags:
        - Exercise
      description: Fetch the exercise with the given Id
      parameters:
        - in: path
          name: exerciseId
          schema:
            type: string
          required: true
          example: 5a04c3471e403f31c973d699
      responses:
        "200":
          description: Returns the routine with ID
  /updateSerie/{serieId}/exercise/{exerciseId}:
    patch:
      tags:
        - Serie
      description: Update the serie with the given Id
      parameters:
        - in: path
          name: serieId
          schema:
            type: string
          required: true
          example: 5a4ea837ae79ef0014fc737f
        - in: path
          name: exerciseId
          schema:
            type: string
          required: true
          example: 5a3eb620260b8700140e500e
      requestBody:
        description: the ISerieUpdate data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reps:
                  type: number
                  example: 10
                weight:
                  type: number
                  example: 12.5
      responses:
        "200":
          description: Returns the exercise with the serie updated and hte updated serie
  /deleteSerie/{serieId}/exercise/{exerciseId}:
    delete:
      tags:
        - Serie
      description: Delete the serie with the given Id
      parameters:
        - in: path
          name: serieId
          schema:
            type: string
          required: true
        - in: path
          name: exerciseId
          schema:
            type: string
          required: true
          example: 5a3eb620260b8700140e500e
      responses:
        "200":
          description: Returns the exercise with the serie deleted and the deleted serie
  /newSerie/{exerciseId}:
    post:
      tags:
        - Serie
      description: Adds a new serie to the exercise with the given Id
      parameters:
        - in: path
          name: exerciseId
          schema:
            type: string
          required: true
          example: 5a3eb620260b8700140e500e
      requestBody:
        description: the suggestedSerie 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reps:
                  type: number
                  example: 10
                weight:
                  type: number
                  example: 12.5
      responses:
        "200":
          description: Returns the exercise with the new serie and the new serie
  /spec:
    get:
      tags:
        - Specification
      responses:
        "200":
          description: Return the API specification
servers:
  - url: /api/v1
