swagger: '2.0'
info:
  description: Balanced Gym App
  title: balanced-gym-app
  version: 1.0.0
basePath: /api/v1
paths:
  '/deleteSerie/{serieId}/exercise/{exerciseId}':
    delete:
      parameters:
        - in: path
          name: serieId
          required: true
          type: string
        - in: path
          name: exerciseId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
      responses:
        '200':
          description: Returns the exercise with the serie deleted and the deleted serie
      tags:
        - Serie
      description: Delete the serie with the given Id
  '/exercise/{exerciseId}':
    get:
      parameters:
        - in: path
          name: exerciseId
          required: true
          type: string
          x-example: 5a04c3471e403f31c973d699
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - Exercise
      description: Fetch the exercise with the given Id
  '/newSerie/{exerciseId}':
    post:
      consumes:
        - application/json
      parameters:
        - in: path
          name: exerciseId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
        - description: the suggestedSerie
          in: body
          name: body
          required: true
          schema:
            properties:
              reps:
                example: 10
                type: number
              weight:
                example: 12.5
                type: number
            type: object
      responses:
        '200':
          description: Returns the exercise with the new serie and the new serie
      tags:
        - Serie
      description: Adds a new serie to the exercise with the given Id
  '/routine/{routineId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - Routine
      description: Fetch the routine with the given Id
  '/routine/{routineId}/muscleGroup/{muscleGroupId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          required: true
          type: string
          x-example: 5dde9b568603d000157b627d
      responses:
        '200':
          description: Returns the routine with ID
      tags:
        - Routine
      description: Fetch the muscleGroup with the given IDs
  '/routine/{routineId}/muscleGroup/{muscleGroupId}/target/{targetId}':
    get:
      parameters:
        - in: path
          name: routineId
          required: true
          type: string
          x-example: 59f0c59d4e55c40d38868034
        - in: path
          name: muscleGroupId
          required: true
          type: string
          x-example: 5dde9b568603d000157b627d
        - in: path
          name: targetId
          required: true
          type: string
          x-example: 5a55152ad9b873001457578f
      responses:
        '200':
          description: Returns the target with ID
      tags:
        - Routine
      description: Fetch the target with the given IDs
  /routines:
    get:
      parameters: []
      responses:
        '200':
          description: Returns all routines
      tags:
        - Routine
      description: Fetch all routines
  /spec:
    get:
      parameters: []
      responses:
        '200':
          description: Return the API specification
      tags:
        - Specification
  '/updateSerie/{serieId}/exercise/{exerciseId}':
    patch:
      consumes:
        - application/json
      parameters:
        - in: path
          name: serieId
          required: true
          type: string
          x-example: 5a4ea837ae79ef0014fc737f
        - in: path
          name: exerciseId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
        - description: the ISerieUpdate data
          in: body
          name: body
          required: true
          schema:
            properties:
              reps:
                example: 10
                type: number
              weight:
                example: 12.5
                type: number
            type: object
      responses:
        '200':
          description: Returns the exercise with the serie updated and hte updated serie
      tags:
        - Serie
      description: Update the serie with the given Id
tags:
  - name: Routine
  - name: Serie
  - name: Exercise

